// <auto-generated />
namespace EDASampleProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changed_datatype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_datatype));
        
        string IMigrationMetadata.Id
        {
            get { return "202201131254561_changed_datatype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
