// <auto-generated />
namespace EDASampleProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class create_staff01_staff02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_staff01_staff02));
        
        string IMigrationMetadata.Id
        {
            get { return "202201130705407_create_staff01_staff02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
